server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

      routes:

        - id: service-jean
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/jean/**

        - id: jean-docs
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/jean/v3/api-docs

        - id: service-marca
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/marca/**

        - id: service-modelo
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/modelo/**

        - id: service-inventario
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/inventario/**

        - id: inventario-docs
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/inventario/v3/api-docs

        - id: service-cliente
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/cliente/**

        - id: cliente-docs
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/cliente/v3/api-docs

        - id: service-carrito
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/carrito/**

        - id: service-producto-carrito
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/producto-carrito/**

        - id: service-venta
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/venta/**

        - id: service-detalle-venta
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/detalle-venta/**

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

springdoc:
  swagger-ui:
    urls:
      - name: Servicio Jean
        url: /api/v1/jean/api-docs

      - name: Servicio Inventario
        url: /api/v1/inventario/api-docs

      - name: Servicio Cliente
        url: /api/v1/cliente/api-docs