server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: service-jean
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/jean/**

        - id: service-marca
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/marca/**

        - id: service-modelo
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/modelo/**

        - id: service-inventario
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/inventario/**

        - id: service-cliente
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/cliente/**

        - id: service-carrito
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/carrito/**

        - id: service-producto-carrito
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/producto-carrito/**

        - id: service-venta
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/venta/**

        - id: service-detalle-venta
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/detalle-venta/**
