spring.application.name=service-envio

server.port= 8092
spring.datasource.url=jdbc:mysql://localhost:3306/bd_envio?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Ruta donde se generará el JSON de la documentación
springdoc.api-docs.path=/api/v1/envio/api-docs
# Título de la documentación
springdoc.swagger-ui.path=/swagger-ui.html